### ISSUE TITLE
签名样式

### ISSUE THREAD

**Issue by fiyeck** [mianxiu/Keylol-Style#5]
文字可能出现显示不全，例如[这个帖子](https://keylol.com/t594988-1-1)的 6 楼的签名：
![20200518115637](https://user-images.githubusercontent.com/57694411/82173125-cf953a00-98fe-11ea-879a-6693bd5ac097.png)
可以通过添加以下样式解决。
```CSS
.post-content-sign * {
    line-height: normal;
}
```
